### ISSUE TITLE
missing README

### ISSUE THREAD

**Issue by Helias** [azerothcore/mod-chat-transmitter#6]

**Comment by BarbzYHOOL** [comment]
nobody knows what this module does, why is it even approved? @Helias

**Comment by Helias** [comment]
because we use it daily on ChromieCraft, it is for discord
@r-o-b-o-t-o

**Comment by BarbzYHOOL** [comment]
ok :D

**Comment by TheSCREWEDSoftware** [comment]
Is there any documenation about this?

**Comment by pangolp** [comment]
> Is there any documenation about this?

I don't think so.

**Comment by TheSCREWEDSoftware** [comment]
Is there possiblity someone explainng how it works? 

From the mod to the sevrer to the discord intregiation

**Comment by pangolp** [comment]
> Is there possiblity someone explainng how it works?
> 
> From the mod to the sevrer to the discord intregiation

If I knew how it works, I would have created the README.md

**Comment by Helias** [comment]
Never installed this on my own but it works as any module.
The discord integration should consist of setting up a discord bot and filling the discord bot information in the conf, from the DiscordGuildId conf you should set the channel where the discord bot sends the message (I guess)
moreover, from the conf, you can see that it requires Eluna db connection.

A readme would help, but usually reading a bit of conf and worst case also the source code you should be able to understand.

meanwhile, @r-o-b-o-t-o, hope you can find some time to write a readme ;-)

**Comment by TheSCREWEDSoftware** [comment]
I see what I was missing then, I was trying to get it to work and understand to get it to work so I could make even if it was a shitty readme so everyone can use it.

(I was missing the eluna part as I thought was optional)
